Update App.tsx
spacey-sooty/ds-linux pull request #1
Opened 2024-07-13 15:06 UTC by SPLATPLAYS

fixed errors

2024-07-14 02:12 UTC, spacey-sooty requested changes

2024-07-14 02:12 UTC, spacey-sooty commented on src/App.tsx
> +import { useState } from "react";
React is not a dependency of this project its a preact project

2024-07-14 02:19 UTC, spacey-sooty commented
This doesn't fix any of the errors btw they are from `e.target.value`

2024-07-15 03:15 UTC, SPLATPLAYS commented
Made some updates, does this work?

2024-07-15 06:09 UTC, spacey-sooty requested changes

2024-07-15 06:09 UTC, spacey-sooty commented on src/App.tsx
> +import { h } from 'preact';
```suggestion
```

2024-07-15 06:09 UTC, spacey-sooty commented on src/App.tsx
> +    };
This approach doesn't fix the issue...

2024-08-20 13:54 UTC, closed without merging